### Register Book - POST /books
POST http://127.0.0.1:3000/books
Content-Type: application/json

{
  "Title": "Clean Architecture",
  "Author": "Robert C. Martin",
  "Isbn": "9780134494166",
  "Stock": 3
}

### Register Loan - POST /loans
POST http://127.0.0.1:3000/loans
Content-Type: application/json

{
  "BookId": "f5b0da38-59b8-4c1a-b90d-f2be36797620",
  "Cpf": "00000000000"
}

### Return Loan - POST /loans/return
POST http://127.0.0.1:3000/loans/return
Content-Type: application/json

{
  "BookId": "f5b0da38-59b8-4c1a-b90d-f2be36797620",
  "Cpf": "00000000000"
}

### List All Books - GET /books
GET http://127.0.0.1:3000/books

### List All Loans - GET /loans
GET http://127.0.0.1:3000/loans
