### Register Book - POST /books
POST http://127.0.0.1:3000/books
Content-Type: application/json

{
  "Title": "Clean Architecture",
  "Author": "Robert C. Martin",
  "Isbn": "9780134494166"
}

### Register Loan - POST /loans
POST http://127.0.0.1:3000/loans
Content-Type: application/json

{
  "BookId": "246b03d6-30b4-4a9e-8812-4e5e8534142c",
  "Cpf": "529.982.247-25"
}
