AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cede-api

  Event-driven e-commerce backend built with serverless architecture using AWS services like Lambda, SNS, and SQS.

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: aws-apigateway/create_order.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /orders
            Method: post

  CancelOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: aws-apigateway/cancel_order.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        CancelOrder:
          Type: Api
          Properties:
            Path: /orders/cancel
            Method: post

  PayOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: aws-apigateway/pay_order.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        PayOrder:
          Type: Api
          Properties:
            Path: /orders/pay
            Method: post
