AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cede-api

  Event-driven e-commerce backend built with serverless architecture using AWS services like Lambda, SNS, and SQS.

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ReservationsCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: aws-apigateway/reservations_create.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        CreateReservation:
          Type: Api
          Properties:
            Path: /reservations
            Method: post

  ReservationsConfirmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: aws-apigateway/reservations_confirm.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        ConfirmReservation:
          Type: Api
          Properties:
            Path: /reservations/{id}/confirm
            Method: post

  ReservationsCancelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: aws-apigateway/reservations_cancel.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        CancelReservation:
          Type: Api
          Properties:
            Path: /reservations/{id}/cancel
            Method: post
