AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cede-api

  Event-driven e-commerce backend built with serverless architecture using AWS services like Lambda, SNS, and SQS.

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: aws-apigateway/post.order.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /orders
            Method: post
